### ISSUE TITLE
Does pyconcrete generate .pyc files during execution, if yes which location?

### ISSUE THREAD

**Issue by halil-karabacak** [Falldog/pyconcrete#101]
Hi, first of all thanks for the effort.

My question is simple, I believe that pyconcrete should convert .pye files to at least .pyc file at some point. But I simply couldn't find the location because, probably, pyconcrete deletes the .pyc files after execution, which is too short my tracker cannot detect. 

I also added delay during execution to find the location and tracked the whole fs but still none.

Thanks a lot!

**Comment by Falldog** [comment]
pyconcrete decrypt and loaded in memory, will not create any file at runtime
