### ISSUE TITLE
Error opening pye-protected models.py and migrations/* files

### ISSUE THREAD

**Issue by sfcl** [Falldog/pyconcrete#104]
If you encrypt the py files of a Django project by running the command
```
pyconcrete-admin.py compile \
        --source=/code/ \
        --pye \
        --remove-py \
        --remove-pyc \
        -i wsgi.py manage.py
```
then the `python manage.py migrate` command does not see the migration files and files with database models. How to protect an entire Django project?

**Comment by Falldog** [comment]
ref: https://github.com/Falldog/pyconcrete#partial-encrypted-pyconcrete-as-lib
You need to modify your entrypoint file `manage.py`, it need to import pyconcrete at the beginning. and the migration will get working
