### ISSUE TITLE
Trying to license and protect some software I created

### ISSUE THREAD

**Issue by jimmycorkhill** [Falldog/pyconcrete#13]
I'm looking for ways to encrypt my code, compile it and lock it to a user's computer. Will I also be able to compile my script into an exe without a problem even if I use your encryption?

**Comment by Falldog** [comment]
@jimmycorkhill pyconcrete [Apache License](https://github.com/Falldog/pyconcrete/blob/master/LICENSE) is fine for commercial use, so there is no problem.
:)

**Comment by jimmycorkhill** [comment]
Sorry, I mean license as in serial codes and license keys.

I am selling some software for a game, but there will be attempts to hack it and distribute it for free.

I'm attempting to lock the script to a single user's PC and I want to stop the software being easily reverse-engineered.

Does pyconcrete compile to .exe at all?

**Comment by Falldog** [comment]
pyconcrete doesn't support the function currently. Short term, you could try on compile .exe by yourself. Reference [Embedded python](https://docs.python.org/2/extending/embedding.html#very-high-level-embedding)

Compile `.exe` in embedded python. The source `.c` maybe look like below
```
#include <Python.h>

int main(int argc, char *argv[])
{
  Py_SetProgramName(argv[0]);  /* optional but recommended */
  Py_Initialize();
  PyRun_SimpleString("import pyconcrete\n"
                     "import src\n"
                     "src.main()\n");
  Py_Finalize();
  return 0;
}
```

Long term, pyconcrete may include this feature in `setup.py`

**Comment by Falldog** [comment]
Hi @jimmycorkhill 
You can use new `pyconcrete` executable file to distribute different license key (pyconcrete) to customers
