### ISSUE TITLE
windows anaconda4.4+python3.6 +vs2015  compile error? 

### ISSUE THREAD

**Issue by gxd1994** [Falldog/pyconcrete#16]
c:\programdata\anaconda3\include\pytime.h(151): error C2061: 语法错误: 标识符“_PyTime_GetMonotonicClock”
c:\programdata\anaconda3\include\pytime.h(151): error C2059: 语法错误:“;”
c:\programdata\anaconda3\include\pytime.h(151): error C2059: 语法错误:“<parameter-list>”
c:\programdata\anaconda3\include\pytime.h(167): error C2143: 语法错误: 缺少“)”(在“*”的前面)
c:\programdata\anaconda3\include\pytime.h(167): error C2143: 语法错误: 缺少“{”(在“*”的前面)
c:\programdata\anaconda3\include\pytime.h(168): error C2371: “_Py_clock_info_t”: 重定义；不同的基类型
c:\programdata\anaconda3\include\pytime.h(160): note: 参见“_Py_clock_info_t”的声明
c:\programdata\anaconda3\include\pytime.h(168): error C2143: 语法错误: 缺少“;”(在“*”的前面)
c:\programdata\anaconda3\include\pytime.h(168): error C2059: 语法错误:“)”
c:\programdata\anaconda3\include\pytime.h(179): error C2143: 语法错误: 缺少“)”(在“*”的前面)
c:\programdata\anaconda3\include\pytime.h(179): error C2143: 语法错误: 缺少“{”(在“*”的前面)
c:\programdata\anaconda3\include\pytime.h(180): error C2371: “_Py_clock_info_t”: 重定义；不同的基类型
c:\programdata\anaconda3\include\pytime.h(160): note: 参见“_Py_clock_info_t”的声明
c:\programdata\anaconda3\include\pytime.h(180): error C2143: 语法错误: 缺少“;”(在“*”的前面)
c:\programdata\anaconda3\include\pytime.h(180): error C2059: 语法错误:“)”
c:\programdata\anaconda3\include\pyhash.h(64): error C2061: 语法错误: 标识符“uint64_t”
c:\programdata\anaconda3\include\pyhash.h(64): fatal error C1003: 错误计数超过 100；正在停止编译
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

how to solve? thx

**Comment by Falldog** [comment]
I had update setup.py script, it should be fixed
