### ISSUE TITLE
Django encryption

### ISSUE THREAD

**Issue by ppiccolo** [Falldog/pyconcrete#18]
Hello, 

I like to know if is possible to encrypt also a Django/Celery project ?

Thanks

**Comment by Falldog** [comment]
@ppiccolo 
I'm not sure `celery` project with pyconcrete

I think it should be worked for django + uwsgi

uwsgi entry point should be `wsgi.py` of django project, need take care below
* wsgi.py must can't be encrypted
* import pyconcrete at beginning
* example `wsgi.py`
    ```python
    import pyconcrete
    import os
    from django.core.wsgi import get_wsgi_application
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "your_project.settings")
    application = get_wsgi_application()
    ```
* other files should be encrypted as *.pye

I think I will add an example for django project in pyconcrete source in future

**Comment by ppiccolo** [comment]
Ok I'll give it a try.

Thank you

**Comment by Falldog** [comment]
Already add an example for Django, close thie issue.

**Comment by Falldog** [comment]
leave `manager.py` & `wsgi.py` as plaintext file (non encrypted)
follow the README, pyconcrete should be importted in the entry file
and you can just execute as below
```
$ ./manage.py migrate
```
