### ISSUE TITLE
Last versions of pyconcrete corrupts pip/python on some environment...

### ISSUE THREAD

**Issue by JeanLescut** [Falldog/pyconcrete#2]
Hello Falldog,

Thanks a lot for your amazing work.
I found out that I couldn't use pip anymore on my machine. I struggled during days to find why, and it seems that pyconcrete brings some issue for its latest versions (since it create a .pth file to auto-import itself...)

However, this bug only concerns some distribution.
Here is a code that will allow you to reproduce the bug on different environment : [pyconcrete_corrupts_python.tar.gz](https://github.com/Falldog/pyconcrete/files/609287/pyconcrete_corrupts_python.tar.gz)

For example, on Debian-jessie + Miniconda 4.0.5 + pyconcrete (#commit >= 095e7605e1) => Bug
For Debian-jessie + Python2.7 + pip9.0.9 + pyconcrete => There is no bug

I will continue to work on it during my free time and keep you informed (I may will come up with a pull request if I can fix it by myself... ;) )

**Comment by Falldog** [comment]
Hi JeanLescut,

I saw the `pyconcrete_corrupts_python.tar.gz`
It's awesome on building by docker!!!

I think this issue should cause by `pyconcrete import hook`, it doesn't handle all cases, ex: relative import, ... etc. Maybe put a .pth is not a good idea for now.

I know there is some issue in pyconcrete import, but I have no time to figure it out currently. Maybe a few weeks later, I will get some time to check it out. If you have free time, welcome to help to fix this issue. :)

**Comment by Falldog** [comment]
Hi @JeanLescut,

Fix the issue at b31520a240c203eee2e2f73545ac57c93f06f44c
I had run the script again, and pip is work normally.
You can check it again.

If there is no other concern, I will close this issue. :)
