### ISSUE TITLE
How do you remove this?

### ISSUE THREAD

**Issue by BeebBenjamin** [Falldog/pyconcrete#27]
How do I uninstall pyconcrete.  I tried using pip but now it throws an error.

**Comment by Falldog** [comment]
If you install by `pip`
```
pip uninstall pyconcrete
```

and make sure the file `pyconcrete.pth` not in your python's `site-packages`, you can find the path by below command
```
python -m site --user-site
```

BTW
crontab execution fail
it should be PATH issue, it's different for crontab and user shell
you can setup PATH at crontab beginning to make sure python/pyconcrete under the PATH

**Comment by Falldog** [comment]
@BeebBenjamin Does the steps help you?
I will close the issue if no responses

**Comment by BeebBenjamin** [comment]
I don't know.  I re-installed Linux!
