### ISSUE TITLE
_pyconcrete.pyd location?

### ISSUE THREAD

**Issue by jaykishan007** [Falldog/pyconcrete#28]
Could you please tell me the location of key information stored? If it locates on same machine, would it be possible for someone to look over and be able to decrypt the code?

**Comment by Falldog** [comment]
The key will store in `_pyconcrete.pyd`, it can't be viewed it directly in HEX view
Please reference the [stackoverflow thread ](https://stackoverflow.com/questions/1356896/how-to-hide-a-string-in-binary-code)

There is always a way to decrypt .pye files, but pyconcrete just make it harder.
