### ISSUE TITLE
Python version doesn't match with magic

### ISSUE THREAD

**Issue by lean0708** [Falldog/pyconcrete#29]
Is this error related to a python version mismatch? (i mean, compiled with a version 2.7.x and deployed with version 2.7.n)

**Comment by Falldog** [comment]
Yes, because of `.pye` compress from `.pyc`, this is `.pyc` limitation

**Comment by federicoemartinez** [comment]
Would it make sense to compress from .py instead of pyc? We would like to use pyconcrete in production and it would be great if we can support multiple python versiones, because it can be tricky to manage the python version installed in servers that are not ours.

**Comment by Falldog** [comment]
@federicoemartinez it's recommended to use `.pyc` to encrypt `.pye` for security reason. It's not safe about encrypt `.py` to `.pye`, because pyconcrete will decrypt it at runtime then execute it. I think that encrypt `.pyc` to `.pye` will be more security than `.py`

**Comment by federicoemartinez** [comment]
I got it, thanks!
