### ISSUE TITLE
Memory has been released

### ISSUE THREAD

**Issue by zhaohainan666** [Falldog/pyconcrete#36]
https://github.com/Falldog/pyconcrete/blob/49352b2c3a725e48e53ac27a8f524b9d7af808f1/src/pyconcrete_exe/pyconcrete_exe.c#L142

py_content has been released in Py_DECREF(py_args)

**Comment by zhaohainan666** [comment]
According to [the Python documentation](https://docs.python.org/2/c-api/tuple.html?#c.PyTuple_SetItem), `PyTuple_SetItem` steals a reference to the inserted object. So you shouldn't dereference `py_content` manually since `py_args` now owns `py_content`.

I think you should remove the `Py_DECREF(py_content);` line instead of `Py_DECREF(py_args);` line.

**Comment by SashaAVCO** [comment]
Ok.
Just posted the resulted source code (that works Ok for me at least now both for simple example and for complex project with many-many *.python modules):

https://github.com/Falldog/pyconcrete/issues/31
