### ISSUE TITLE
Bad Marshall data

### ISSUE THREAD

**Issue by dtj20** [Falldog/pyconcrete#39]
Running pyconcrete files gives me the following error "ValueError: bad marshal data (unknown type code)"

This happens with any file since I did a reinstall of pyconcrete to change the secret password. Before I did the reinstall I deleted all pyconcrete traces from the machine and deleted the generated pye files. Afterwards I ran the setup,py script and set a new passphrase, then recompiled the .py files to .pye file with following command

pyconcrete-admin.py compile --source=file.py --pye

and running the file with

pyconcrete file.pye

I'm using python (Python 2.7.12 (default, Dec  4 2017, 14:50:18) This is set as the machine default.

**Comment by Falldog** [comment]
How do you install pycocnrete? setup.py or pip?
I can't reproduce the issue from my environment
