### ISSUE TITLE
Decrypting .pye files

### ISSUE THREAD

**Issue by ddfabbro** [Falldog/pyconcrete#40]
I'm using pyconcrete as library using the example given in the `README`.

My project has the following structure:
```
.
└── myproject
    ├── main.py
    ├── pyconcrete
    └── src
        ├── module1.pye
        ├── module2.pye
        └── module3.pye
```
What is the process to decrypt `module1.pye`, `module2.pye`, etc, given that the passphrase is know?

Now, suppose I distribute `myproject` to end user.

What you be the process for them to decrypt `module1.pye`, `module2.pye`, etc?

**Comment by Falldog** [comment]
`main.py` need to import pyconcrete
ex: [example django manage.py](https://github.com/Falldog/pyconcrete/blob/master/example/django/pye_web/manage.py)

Once your script import pyconcrete, it will hook importer for decrypt `.pye`. So you must import `pycocnrete` before any module be encrypted as `.pye`

**Comment by ddfabbro** [comment]
I did so, and it works perfectly! But my question is, once I have my `main.py` working and remove all `.py` files, how can my `.pye` get decrypted be me using the passphrase I defined on setup step?

How about if I distribute `myproject` to end user, he will also have `_pyconcrete.pyd`. How do I know my code is safe? Where is this file and what can I do with it?

**Comment by Falldog** [comment]
As README mentioned,
encrypt & decrypt secret key record in `_pyconcrete.pyd` (like DLL or SO) the secret key would be hidden in binary code, can't see it directly in HEX view.

There is always a way to decrypt .pye files, but pyconcrete just make it harder.
