### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by msusare** [Falldog/pyconcrete#46]
hi ,
Running pyconcrete files gives me the following error "ValueError: bad marshal data (unknown type code)"

I am using Mac machine .

I have compiles script with following code:
pyconcrete-admin.py compile --source=main.py --pye

and running the file with
pyconcrete main.pye

I'm using python (Python 2.7.15)

I have installed pyconcrete with setup.py.

**Comment by Falldog** [comment]
Hi,
Which pyconcrete version?
It should be encrypted & executed by different python version issue.
Please help to make sure you encrypt & execute by the same python version
