### ISSUE TITLE
Deploy code

### ISSUE THREAD

**Issue by ccfiel** [Falldog/pyconcrete#5]
I did successfully encrypt in my development laptop but how will deploy my encrypted code to other laptop/pc? 

What I tried so far is install the pyconcrete in the other pc/laptop but its asking me again the passphrase which it will defeat the purpose.

**Comment by Falldog** [comment]
pyconcrete encryption will use the passphrase inputted at installation, and store it in `_pyconcrete.so`

So, you can package pycocnrete by yourself which you install on your machine, the `pycocnrete` & .pye files could run together on other pc/laptop, and make sure your machine env is same as other pc/laptop. `pyconcrete` library is machine dependent. If you need to deploy on different machine type(ex, linux, mac, windows) you need to pre-compile all of it first.

**Comment by ccfiel** [comment]
@Falldog when you say package pyconcrete. Do I just need to copy /usr/local/lib/python2.7/dist-packages/pyconcrete to the folder where I will distribute the program?  I still did not get how to deploy pyconcrete to other pc/laptop :(

**Comment by Falldog** [comment]
I think you could try to install pyconcrete as local library
Please reference: https://github.com/Falldog/pyconcrete#usage-pyconcrete-as-lib

your project layout may like below
```
main.py       # import pyconcrete and your lib
pyconcrete/*  # put pyconcrete lib in project root, keep it as original files
src/*.pye     # your libs
```
Just compress the folder and deploy on your target machine


Deploy on target machine steps
1. install python 
2. install other packages you needed (maintain by pip)
3. copy & decompress your source code and pyconcrete
4. execute your program `python main.py`
Note: make sure the python version is same as your machine

**Comment by ccfiel** [comment]
Thanks @Falldog! Great project! :)
