### ISSUE TITLE
Issue at runtime - SyntaxError Non-ASCII character in line 1 of main.pye file

### ISSUE THREAD

**Issue by martinbel** [Falldog/pyconcrete#52]
Installation and compilation worked with no errors.

`pyconcrete-admin.py compile --source=main.py  --pye`

At runtime I get this error

`main.pye -p 0.5 -n 0.5 -d 0`
SyntaxError: Non-ASCII character \xf7 in file main.pye on line 1...

The main.py file has the encoding defined as UTF-8 and has no non-ascii characters. 
I'm using python 3.5, OS is Raspbian.

**Comment by Falldog** [comment]
Please execute the command as below
```
pyconcrete main.pye -p 0.5 -n -.5 -d 0
```
main.pye is encrypted file, need `pyconcrete` to execute it.
