### ISSUE TITLE
IMHO you should remove default key and throw error, when key is not provided during installation

### ISSUE THREAD

**Issue by janjur** [Falldog/pyconcrete#58]
https://github.com/Falldog/pyconcrete/blob/847ab11407a087e5f07d942962d45baaa7951234/src/config.py#L9

**Comment by Falldog** [comment]
Thanks for your suggestion. I will remove default key setting
for both support install by `pip` and setup.py, need more testing
1. `pip` install, I need to try read the password from os.env rather than STDIN
2. setup.py should get the ability to read password from STDIN
