### ISSUE TITLE
Pyconcrete for Reusable Django Apps

### ISSUE THREAD

**Issue by lucreziopancrazio** [Falldog/pyconcrete#59]
Hi it's possible to use it for reusable apps?
I followed this guide https://docs.djangoproject.com/en/2.2/intro/reusable-apps/

Everything works fine and I've built pip packages. I want to protect my code so I've installed pyconcrete in main project and executed 'pyconcrete-admin compile etc'. 
It works and gave me pye files so I tried 'pyconcrete-admin release' and pyconcrete created a tar.gz packag. But if I extract the code is in clear. How can I encrypt this code?

**Comment by Falldog** [comment]
Sorry, the purpose of `pyconcrete-admin release` is for release `pyconcrete` project, not for your django project.

Django reusable-apps package by `setup.py sdist`. If you want package your own project (not pyconcrete), you should read setup.py document, study how to collect the files/scripts you want.

**Comment by lucreziopancrazio** [comment]
Thanks for the answer. I found some documentation about collecting files for setup.py (just include all interested files in MANIFEST.in) so in package I put every pye file, but during pip installation they are ignored. Do you have any suggestion?

**Comment by Falldog** [comment]
You can try to customize install class
reference https://github.com/Falldog/pyconcrete/blob/master/setup.py#L250
