### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by Aditya715** [Falldog/pyconcrete#63]
I am encrypting a project using pyconcrete but in venv. Now I'm trying to drop all the venv in another pc/laptop. When I run the code for that it gives me threading error and pushing the whole thing on the local interpreter. /usr/lib/python/threading.py

**Comment by Falldog** [comment]
1. What pycocnrete version you install?
2. What command make you get the threading error? You run in another venv? or use system default python?
