### ISSUE TITLE
Why can the code run correctly without "import pyconcrete" in the main.py?

### ISSUE THREAD

**Issue by animebing** [Falldog/pyconcrete#64]
Thanks for your awesome work, which helps me a lot, but I still find something I can't understand. I use `pyconcrete-admin.py` to encrypt my all `.py` file except `main.py`, but when I run my code without `import pyconcret` in `main.py`, it can still run correctly, can you tell me why this happens, thanks anyway.

**Comment by Falldog** [comment]
I think you installed pyconcrete as site-packages, it will generate `pyconcrete.pth` in your site-packages, python will default load all *.pth at launch. So your `main.py` execute by default python executable, it will load `pyconcrete.pth` and then import pyconcrete automatically.

**Comment by animebing** [comment]
@Falldog Thank you for your quick reply, what should I do if I don't want this characteristic, may remove 'pyconcrete.pth'?

**Comment by Falldog** [comment]
You should follow the README https://github.com/Falldog/pyconcrete#partial-encrypted-pyconcrete-as-lib, install pyconcrete as local library rather than global package

You can uninstall pyconcrete or delete pyconcrete.pth to revise current environment

**Comment by animebing** [comment]
@Falldog I have deleted pyconcrete.pth and it works, maybe I should install it as a local library. I really appreciate your kind and quick reply.

**Comment by Falldog** [comment]
@animebing for current pyconcreate installation behavior not allow setup passphrase after installation. Please make your shell script to use credentials mechanism to install pyconcrete.

for your reference: https://unix.stackexchange.com/questions/212329/hiding-password-in-shell-scripts

**Comment by animebing** [comment]
I don't mean to setup passphrase after installation, I just want to hardcode the passphrase in the shell script just like you do in pip install, but here I want to use python setup.py install instead of pip install.

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Falldog** [comment]
Well noted
Please give it a try 
```
python setup.py install --passphrase=<your passphrase>
```

**Comment by animebing** [comment]
@Falldog it works, thanks.
