### ISSUE TITLE
I want to run pye in a script

### ISSUE THREAD

**Issue by KohnoseLami** [Falldog/pyconcrete#79]
I have a question about "pyconcrete", is it possible to call it from a different file like import?
I want to run pye in an environment that cannot be called from the console.

**Comment by Falldog** [comment]
You could import `pyconcreate` python package as library
```
import pyconcrete
if __name__ == '__main__':
    pass
```
You could not import `pyconcrete` exec file, rather that you can execute it in command line
linux shell script
```
$! /bin/bash
echo "before run"
pyconcrete main.pye
echo "after run"
```

**Comment by KohnoseLami** [comment]
I'm sorry, this question is, "Can you execute pye like pyc?" ...

"pyc" can be imported as a module from another file, can "pye" do the same?

**Comment by Falldog** [comment]
If you want to share your module to others, must share with pyconcrete module. Because the encryption key store in `_pyconcrete.so` build on your machine when you install pyconcrete.
