### ISSUE TITLE
build on mingw + winXP

### ISSUE THREAD

**Issue by hamada2029** [Falldog/pyconcrete#8]
Builded on mingw(winXP), and failed.
But I edited source file(roughly). Build successful.

setup.py
```
# comment out
# if sys.platform == 'win32':
#     include_dirs.append(join(EXT_SRC_DIR, 'include_win'))
```

/src/pyconcrete_ext/openaes/src/oaes.c
```
// ignore if block
#if defined(_WIN32) && !defined(__SYMBIAN32__)
#else
	#ifndef _fprintf_p
		#define _fprintf_p fprintf
	#endif // _fprintf_p
#endif
#define _fprintf_p fprintf //added
 ```

I think these options need just for MSVC.
Thanks.

**Comment by Falldog** [comment]
@hamada2029 how you assign mingw as your compiler? rather than MSVC?
If you have time to refine the code, Pull Request is welcome. :)

**Comment by hamada2029** [comment]
I am using MinGW Installation  Manager.
Because I could not find handy-size MSVC library on XP.

Please check my pull request.
