### ISSUE TITLE
Password change

### ISSUE THREAD

**Issue by michalmalara** [Falldog/pyconcrete#80]
Hi,

Is it possible to change the password? I want to encrypt my files on one device and run it on another one, but I forget what password I passed during pyconcrete installation. 

Also, can you tell me where is _pyconcrete.pyd file stored? I have a Debian based Linux system.

**Comment by Falldog** [comment]
1. change password
The password will be stored in `_pyconcrete.pyd`, you can uninstall pyconcrete, and install again.

2. Check _pyconcrete.pyd path
```
import pyconcrete
print(pyconcrete.__path__)
```
