### ISSUE TITLE
Encryption for installed packages

### ISSUE THREAD

**Issue by eggcracker** [Falldog/pyconcrete#81]
Hi, is there anyway to automatically apply pyconcrete to the packages that are installed with pip? Currently I find their installation location and apply pyconcrete manually.

**Comment by Falldog** [comment]
No, there is no way to do it now.

Maybe you can try to install package by pip virtualenv, and you be able to find all the package which install by pip and encrypt it at once time

**Comment by eggcracker** [comment]
Thank you for the clarification!
