### ISSUE TITLE
whether encrypted pye file can be decrypted to pyc file?

### ISSUE THREAD

**Issue by animebing** [Falldog/pyconcrete#83]
After I install `pyconcrete` using `python setup.py install`, in the `__init__.py`, I find `encrypt_file` and `decrypt_file`, I know `encrypt_file` is used in `pyconcrete-admin.py` to encrypt `pyc` to `pye`, so whether I can use `decrypt_file` to decrypt `pye` to `pyc`, if this is the case, the security of the code can not be guaranteed.

**Comment by Falldog** [comment]
The decrypt_file has not be implemented, it will do nothing now.
