### ISSUE TITLE
Testing application

### ISSUE THREAD

**Issue by michalmalara** [Falldog/pyconcrete#85]
Hi! Is it possible to run tests of the encrypted application that are written in pytest? If yes, can you please write how to do that?

**Comment by Falldog** [comment]
I'm not sure your scenario
attach the testing as below for pyconcrete exe execute .pye and check output 
https://github.com/Falldog/pyconcrete/blob/master/test/test_exe.py

**Comment by vujadeyoon** [comment]
Dear all,

You can find the easy example in my repository, [Pyconcrete-Python](https://github.com/vujadeyoon/Pyconcrete-Pythonl), where the pyconcrete is utilized to protect the own visible python script codes (e.g. PyTorch script codes.).
